config/routes.rb
Rails.application.routes.draw do
  resources :announcements, only: [:index, :show]
  get 'redeem', to: 'redeem#index'
  put 'redeem/consume'

  get 'uploader/image'
  namespace :admin do
      resources :accounts
      resources :admin_tiers, except: :index
      resources :admin_tier_permissions, except: :index
      resources :beta_codes
      resources :chats, except: :index
      resources :chat_users
      resources :group_chats, except: :index
      resources :legacy_users, except: :index
      resources :messages, except: :index
      resources :announcements

      root to: "accounts#index"
    end
  resources :messages, except: [:index]

  resources :chat, only: [:show, :edit, :update], controller: "chats" do
    member do
      get 'users'
      get 'log'
      patch 'presence'
      patch 'me'
    end
  end
  resources :chats, except: :show do
    collection do
      get 'subscribed'
      get 'visited'
      get 'searched'
      get 'owned'
    end
  end

  devise_for :accounts, controllers: { registrations: 'registrations' }

  post 'uploader/image'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "announcements#index"
end

app/controllers/redeem_controller.rb
class RedeemController < ApplicationController
  before_action :authenticate_account!
  before_action :set_beta_code

  def consume
    if @beta_code
      respond_to do |format|
        format.html { redirect_to redeem_path, notice: "This account already has beta access." }
        format.json { render :index, status: :unprocessable_entity }
      end
    else
      code = beta_code_params
      @beta_code = BetaCode.find_by(code: code, account_id: nil)
      if @beta_code
        @beta_code.account = current_account
        respond_to do |format|
          if @beta_code.save
            format.html { redirect_to redeem_path, notice: "Beta access obtained." }
            format.json { render :index, status: :ok }
          else
            format.html { redirect_to redeem_path, status: :unprocessable_entity }
            format.json { render json: @beta_code.errors, status: :unprocessable_entity }
          end
        end
      else
        respond_to do |format|
          format.html { redirect_to redeem_path, status: :unprocessable_entity }
          format.json { render :index, status: :unprocessable_entity }
        end
      end
    end
  end

  private 
    def set_beta_code
      @beta_code = current_account.beta_code
    end

    def beta_code_params
      params.require(:code)
    end
end

app/helpers/redeem_helper.rb
module RedeemHelper
end

app/views/redeem/_form.html.erb
<div class="flex flex-col items-center h-screen overflow-hidden pt-8">
    <div class="w-full p-6 bg-base-200 border-t-4 border-accent rounded-md shadow-md border-top lg:max-w-lg">
        <%= form_with(url: redeem_consume_path, html: { method: :put }, class: "space-y-4") do |f| %> 
            <div class="field">
              <label class="label">
                  <span class="text-base label-text">Beta Code</span>
              </label>
              <%= f.text_field :code, autofocus: true, autocomplete: "beta-code", class: "w-full input input-bordered bg-base-300 focus:bg-base-300" %>
            </div>
            <div class="pt-2">
                <%= f.submit "Apply", class: "btn btn-block btn-accent" %>
            </div>
        <% end %>
    </div>
</div>

app/views/redeem/index.html.erb
<% if @beta_code %>
    <div class="flex flex-col items-center h-screen overflow-hidden pt-8">
        <div class="w-full p-6 bg-base-200 border-t-4 border-accent rounded-md shadow-md border-top lg:max-w-lg">
            <div class="space-y-4">
                <div class="field">
                    <label class="label">
                        <span class="text-base label-text">Beta Code</span>
                    </label>
                    <input disabled type="text" class="w-full input input-bordered bg-base-300 focus:bg-base-300" value="<%= @beta_code.code %>">
                </div>
                <div class="field">
                    <label class="label">
                        <span class="text-base label-text">Origin</span>
                    </label>
                    <input disabled type="text" class="w-full input input-bordered bg-base-300 focus:bg-base-300" value="<%= @beta_code.origin %>">
                </div>
            </div>
        </div>
    </div>
<% else %>
    <%= render "redeem/form" %>
<% end %>